"""Add content_label field to files table

Revision ID: 20a0305f8b34
Revises: 1ed2cf95d9f0
Create Date: 2022-11-30 19:08:07.575677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a0305f8b34'
down_revision = '46a278193a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('content_label', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'content_label')
    # ### end Alembic commands ###
